[package]
name = "term-specialized-impl-gen"
version = { workspace = true }
edition = { workspace = true }
description = "Generation of trait implementations that implement traits for specialized data structures that implement a language"

[dependencies]
codegen-component = { path = "../codegen-component" }
extension-autobox = { path = "../extension-autobox" }
langspec = { path = "../langspec" }
langspec-rs-syn = { path = "../langspec-rs-syn" }
rustgen-utils = { path = "../rustgen-utils" }
term-specialized-gen = { path = "../term-specialized-gen" }
term-trait-gen = { path = "../term-trait-gen" }
transitive-ccf = { path = "../transitive-ccf" }
words = { path = "../words" }
quote = { workspace = true }
syn = { workspace = true }
tree-identifier = { path = "../tree-identifier" }

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
term = { path = "../term" }
tymetafuncspec-core = { path = "../tymetafuncspec-core" }
