[package]
name = "term-specialized-gen"
version = { workspace = true }
edition = { workspace = true }
description = "Code generation for a family of Rust data structures that together implement a language; considered specialized to distinguish from dynamic typing"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen-component = { path = "../codegen-component" }
langspec-rs-syn = { path = "../langspec-rs-syn" }
langspec = { path = "../langspec" }
rustgen-utils = { path = "../rustgen-utils" }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
term = { path = "../term" }
tymetafuncspec-core = { path = "../tymetafuncspec-core" }
