[package]
name = "transitive-ccf"
version = "0.1.0"
edition = { workspace = true }
description = "CCF (Canonically Constructible From) analysis algorithms and data types"

[dependencies]
langspec = { path = "../langspec" }
term = { path = "../term" }
rustgen-utils = { path = "../rustgen-utils" }
memo = { path = "../memo/memo" }
aspect.path = "../aspect"

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
tymetafuncspec-core = { path = "../tymetafuncspec-core" }
