[package]
name = "memo-with-references"
version.workspace = true
edition.workspace = true
description = "A memoization proc macro that changes function signatures to accept a cache and return a reference to data in the cache"

[lib]
proc-macro = true


[dependencies]
bumpalo.workspace = true
expect-test.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
trybuild.workspace = true
