[package]
name = "term-bridge-gen"
version = { workspace = true }
edition = { workspace = true }
description = "Generation of code that bridges between a generated language and a generated extension of that language"

[dependencies]
codegen-component = { version = "0.1.0", path = "../codegen-component" }
langspec = { path = "../langspec" }
langspec-rs-syn = { path = "../langspec-rs-syn" }
quote = { workspace = true }
rustgen-utils = { path = "../rustgen-utils" }
syn = { workspace = true }
term-specialized-gen = { version = "0.1.0", path = "../term-specialized-gen" }
term-specialized-impl-gen = { version = "0.1.0", path = "../term-specialized-impl-gen" }
term-trait-gen = { version = "0.1.0", path = "../term-trait-gen" }
words = { version = "0.1.0", path = "../words" }
tree-identifier = { path = "../tree-identifier" }
memo.path = "../memo/memo"
