[package]
name = "term-trait-gen"
version = { workspace = true }
edition = { workspace = true }
description = "Generation of traits that are the same for all families of data structures that correctly implement a language"

[dependencies]
codegen-component = { path = "../codegen-component" }
langspec-rs-syn = { path = "../langspec-rs-syn" }
langspec = { path = "../langspec" }
rustgen-utils = { path = "../rustgen-utils" }
words = { path = "../words" }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
langspec-examples = { path = "../langspec-examples" }
term = { path = "../term" }
