[package]
name = "term-pattern-match-strategy-provider-gen"
version = { workspace = true }
edition = { workspace = true }
description = "Generation of pattern-matching strategies"

[dependencies]
codegen-component = { path = "../codegen-component" }
langspec-rs-syn = { path = "../langspec-rs-syn" }
langspec = { path = "../langspec" }
rustgen-utils = { path = "../rustgen-utils" }
term-trait-gen = { path = "../term-trait-gen" }
words = { path = "../words" }
syn = { workspace = true }

[dev-dependencies]
langspec-examples = { path = "../langspec-examples" }
tymetafuncspec-core = { path = "../tymetafuncspec-core" }
term = { path = "../term" }
