[dependencies.aspect]
path = "../.././aspect"

[dependencies.ccf]
path = "../.././ccf"

[dependencies.fib]
path = "../fib"

[dependencies.fib-pat]
path = "../fib-pat"

[dependencies.file-tmf]
path = "../.././file-tmf"

[dependencies.pattern-tmf]
path = "../.././pattern-tmf"

[dependencies.term]
path = "../.././term"

[dependencies.term-bridge-gen]
path = "../.././term-bridge-gen"

[dependencies.term-pattern-match-strategy-provider-impl-gen]
path = "../.././term-pattern-match-strategy-provider-impl-gen"

[dependencies.term-specialized-gen]
path = "../.././term-specialized-gen"

[dependencies.term-specialized-impl-gen]
path = "../.././term-specialized-impl-gen"

[dependencies.term-trait-gen]
path = "../.././term-trait-gen"

[dependencies.tymetafuncspec-core]
path = "../.././tymetafuncspec-core"

[dependencies.words]
path = "../.././words"

[package]
edition = "2024"
name = "fib-pat-ds"
version = "0.0.0"
