[package]
name = "words"
version = { workspace = true }
edition = { workspace = true }
description = "Functionality related to words, which are symbols that denote abstract concepts that can be implemented by a type of terms in a language or in the extensions of that language, and which can be manipulated at compile time via Rust ZSTs"

[dependencies]
langspec = { path = "../langspec" }
codegen-component = { path = "../codegen-component" }
langspec-rs-syn = { path = "../langspec-rs-syn" }
rustgen-utils = { path = "../rustgen-utils" }
syn = { workspace = true }
conslist = { version = "0.1.0", path = "../conslist" }
